<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="MediatR" />
    <ProjectReference Include="..\..\..\BuildingBlocks\MicroShop.BuildingBlocks.Application\MicroShop.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\MicroShop.Inventory.Domain\MicroShop.Inventory.Domain.csproj" />
  </ItemGroup>
</Project>
