<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <ProjectReference Include="..\..\..\BuildingBlocks\MicroShop.BuildingBlocks.Infrastructure\MicroShop.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\MicroShop.Catalog.Application\MicroShop.Catalog.Application.csproj" />
    <ProjectReference Include="..\MicroShop.Catalog.Infrastructure\MicroShop.Catalog.Infrastructure.csproj" />
  </ItemGroup>
</Project>
