<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Confluent.Kafka" />
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <ProjectReference Include="..\..\..\BuildingBlocks\MicroShop.BuildingBlocks.Domain\MicroShop.BuildingBlocks.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\MicroShop.BuildingBlocks.Infrastructure\MicroShop.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Contracts\MicroShop.Contracts\MicroShop.Contracts.csproj" />
    <ProjectReference Include="..\MicroShop.Catalog.Application\MicroShop.Catalog.Application.csproj" />
    <ProjectReference Include="..\MicroShop.Catalog.Domain\MicroShop.Catalog.Domain.csproj" />
  </ItemGroup>
</Project>
