<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <ProjectReference Include="..\MicroShop.BuildingBlocks.Domain\MicroShop.BuildingBlocks.Domain.csproj" />
  </ItemGroup>
</Project>
