{
 "title": "MicroShop",
 "tags": [ "microshop" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "HTTP request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_server_request_duration_seconds_count[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Average HTTP request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_server_request_duration_seconds_sum[5m])) / sum by (job) (rate(http_server_request_duration_seconds_count[5m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": ".NET GC heap size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_heap_size_bytes",
     "legendFormat": "{{job}} {{generation}}"
    }
   ]
  }
 ]
}